### ISSUE TITLE
Challenges of Disinformation in the Era of AI

### ISSUE THREAD

**Issue by bil4444** [g0v/summit2024#11]
The community track session between 10:40-11:40 would be an English session rather than a Mandarin session. The session will have a panelist who does not speak Mandarin.

**Comment by rschiang** [comment]
Hi @bil4444, thanks for the report to the Summit Website Team! As all the information were provided by their designated speakers, if you’re one of the contacts, please reach out to the Session Team directly for session information amendments. 

Hope this helps! :)

**Comment by bil4444** [comment]
The session team (Hello Peter!!) had agreed to change the website on April 27th, but unfortunately the promised change is not delivered. Please help 😭

**Comment by Jia-wei-cui** [comment]
It is my bad....I will deliver the change with other member
